In [1]:
import numpy as np

### 1.	Write a Python Program to Add Two Matrices?

In [7]:
a = np.array([[4,6,8],[7,5,88],[8,5,77]])
b = np.array([[12,43,74],[5,8,3],[8,9,9]])

Sum = np.add(a,b)
print(f'The sum of two matrix \n{a} and \n{b} is \n{Sum}')

The sum of two matrix 
[[ 4  6  8]
 [ 7  5 88]
 [ 8  5 77]] and 
[[12 43 74]
 [ 5  8  3]
 [ 8  9  9]] is 
[[16 49 82]
 [12 13 91]
 [16 14 86]]


### 2.	Write a Python Program to Multiply Two Matrices?

In [8]:
a = np.array([[4,6,8],[7,5,88],[8,5,77]])
b = np.array([[12,43,74],[5,8,3],[8,9,9]])

Sum = np.dot(a,b)
print(f'The Multiplication of two matrix \n{a} and \n{b} is \n{Sum}')

The Multiplication of two matrix 
[[ 4  6  8]
 [ 7  5 88]
 [ 8  5 77]] and 
[[12 43 74]
 [ 5  8  3]
 [ 8  9  9]] is 
[[ 142  292  386]
 [ 813 1133 1325]
 [ 737 1077 1300]]


### 3.	Write a Python Program to Transpose a Matrix?

In [18]:
a = np.array([[4,6,8],[7,5,88],[8,5,77]])

a_transpose = np.transpose(a)
print(f'The transpose of matrix \n{a} is \n{a_transpose}')


The transpose of matrix 
[[ 4  6  8]
 [ 7  5 88]
 [ 8  5 77]] is 
[[ 4  7  8]
 [ 6  5  5]
 [ 8 88 77]]


### 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [22]:
Arr = input("Enter string : ").lower()

words = Arr.split()
words.sort()
for word in words:
    print(word)

Enter string : Sort Words in Alphabetic Order
alphabetic
in
order
sort
words


### 5.	Write a Python Program to Remove Punctuation From a String?

In [23]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

x = input("Enter a string with punctuations")


s = ""
for i in x:
    if i not in punctuations:
        s = s + i

print(s)

Enter a string with punctuationsHello!!!, he said ---and went.
Hello he said and went
